from __future__ import annotations

from src.modules.runtime_waybill_raw_build import (
    _build_waybill_raw_fallback,
    build_waybill_raw_fallback,
)
from src.modules.runtime_waybill_raw_helpers import (
    _is_missing,
    _extract_between_markers,
    _extract_first_ru_date,
    _strip_leading_form_label,
    _text_before_anchor,
    _text_after_anchor,
    _extract_waybill_words_after_anchor,
    _normalize_waybill_total_number,
    _parse_waybill_footer_numeric_token,
    _extract_waybill_footer_totals_from_text,
    _waybill_totals_incoherent,
    _extract_waybill_barcode_from_name,
    _waybill_significant_name_tokens,
    _waybill_group_raw_line_texts,
    _waybill_find_review_row_index,
    _waybill_iter_review_row_windows,
    _split_waybill_raw_cells,
    _waybill_parse_percent_text,
    _normalize_waybill_raw_unit_token,
    _dominant_waybill_repair_unit,
    _waybill_numeric_token_values,
    _waybill_find_tail_unit,
    _waybill_find_tail_unit_with_end,
    _waybill_build_numeric_candidate,
    _waybill_parse_numeric_candidate_from_text,
    _waybill_extract_total_before_note,
    _waybill_parse_inline_numeric_tail,
    _waybill_review_row_candidate_from_window,
    _waybill_trim_window_to_row,
    _waybill_leading_item_code,
    _waybill_trim_window_before_next_barcode,
    _waybill_numeric_review_present,
    _waybill_numeric_review_count,
    repair_waybill_review_items_from_raw,
    repair_waybill_review_item_names_from_raw,
    _looks_like_address_only,
    _has_waybill_header_anchor_noise,
    _waybill_party_payload_suspicious,
    _overlay_waybill_header_fallback,
    _load_waybill_header_number,
    _build_waybill_raw_header_overlay,
    _score_waybill_party_value,
    _split_person_value_pair,
    _waybill_party_candidate_confident,
    _extract_company_name_address,
)

build_waybill_raw_header_overlay = _build_waybill_raw_header_overlay
extract_between_markers = _extract_between_markers
extract_company_name_address = _extract_company_name_address
extract_first_ru_date = _extract_first_ru_date
has_waybill_header_anchor_noise = _has_waybill_header_anchor_noise
load_waybill_header_number = _load_waybill_header_number
looks_like_address_only = _looks_like_address_only
overlay_waybill_header_fallback = _overlay_waybill_header_fallback
score_waybill_party_value = _score_waybill_party_value
split_person_value_pair = _split_person_value_pair
strip_leading_form_label = _strip_leading_form_label
text_after_anchor = _text_after_anchor
text_before_anchor = _text_before_anchor
waybill_party_candidate_confident = _waybill_party_candidate_confident
waybill_party_payload_suspicious = _waybill_party_payload_suspicious

__all__ = [
    "_is_missing",
    "_extract_between_markers",
    "_extract_first_ru_date",
    "_strip_leading_form_label",
    "_text_before_anchor",
    "_text_after_anchor",
    "_extract_waybill_words_after_anchor",
    "_normalize_waybill_total_number",
    "_parse_waybill_footer_numeric_token",
    "_extract_waybill_footer_totals_from_text",
    "_waybill_totals_incoherent",
    "_extract_waybill_barcode_from_name",
    "_waybill_significant_name_tokens",
    "_waybill_group_raw_line_texts",
    "_waybill_find_review_row_index",
    "_waybill_iter_review_row_windows",
    "_split_waybill_raw_cells",
    "_waybill_parse_percent_text",
    "_normalize_waybill_raw_unit_token",
    "_dominant_waybill_repair_unit",
    "_waybill_numeric_token_values",
    "_waybill_find_tail_unit",
    "_waybill_find_tail_unit_with_end",
    "_waybill_build_numeric_candidate",
    "_waybill_parse_numeric_candidate_from_text",
    "_waybill_extract_total_before_note",
    "_waybill_parse_inline_numeric_tail",
    "_waybill_review_row_candidate_from_window",
    "_waybill_trim_window_to_row",
    "_waybill_leading_item_code",
    "_waybill_trim_window_before_next_barcode",
    "_waybill_numeric_review_present",
    "_waybill_numeric_review_count",
    "repair_waybill_review_items_from_raw",
    "repair_waybill_review_item_names_from_raw",
    "_looks_like_address_only",
    "_has_waybill_header_anchor_noise",
    "_waybill_party_payload_suspicious",
    "_overlay_waybill_header_fallback",
    "_load_waybill_header_number",
    "_build_waybill_raw_header_overlay",
    "_score_waybill_party_value",
    "_split_person_value_pair",
    "_waybill_party_candidate_confident",
    "_extract_company_name_address",
    "_build_waybill_raw_fallback",
    "build_waybill_raw_fallback",
    "build_waybill_raw_header_overlay",
    "extract_between_markers",
    "extract_company_name_address",
    "extract_first_ru_date",
    "has_waybill_header_anchor_noise",
    "load_waybill_header_number",
    "looks_like_address_only",
    "overlay_waybill_header_fallback",
    "score_waybill_party_value",
    "split_person_value_pair",
    "strip_leading_form_label",
    "text_after_anchor",
    "text_before_anchor",
    "waybill_party_candidate_confident",
    "waybill_party_payload_suspicious",
]
