from __future__ import annotations

from src.modules.runtime_doc_type_detection import hard_signal_doc_type, segment_doc_type
from src.modules.runtime_segment_builder import build_segments, build_segments_v2, select_structure_profile
